# Generated by Django 4.0.3 on 2022-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_define'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createblok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('youblok', models.CharField(max_length=250)),
            ],
        ),
    ]
