# Generated by Django 4.0.3 on 2022-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_createblok'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblok',
            name='photo',
            field=models.ImageField(default=2, upload_to='myimage'),
            preserve_default=False,
        ),
    ]
